enum Servidores {
  //
  airt(
    key: 'airt',
    professor: true,
    ativo: true,
    nome: "Airton Bodstein de Barros",
    curto: "Airton",
    siape: "306380-1",
    celular: 0,
    cpf: 0,
    email: "bodstein@vm.uff.br",
    sala: "Non si sá",
    masculino: true,
  ),
  //
  camb(
    key: 'camb',
    professor: true,
    ativo: true,
    nome: "Odivaldo Cambraia Alves",
    curto: "Cambraia",
    siape: "699056-3",
    celular: 0,
    cpf: 23639628268,
    email: "odivaldocambraia@id.uff.br",
    sala: "309",
    masculino: true,
  ),
  //
  carl(
    key: 'carl',
    professor: true,
    ativo: true,
    nome: "Carlos Andres Ortiz Bravo",
    curto: "Ortiz",
    siape: "2285915",
    celular: 0,
    cpf: 0,
    email: "carlosortiz@id.uff.br",
    sala: "511",
    masculino: true,
  ),
  //
  caue(
    key: 'caue',
    professor: true,
    ativo: true,
    nome: "Cauê Torres de Oliveira Guedes Costa",
    curto: "Cauê",
    siape: "119388-9",
    celular: 0,
    cpf: 11610969731,
    email: "cauecosta@id.uff.br",
    sala: "302B",
    masculino: true,
  ),
  //
  edua(
    key: 'edua',
    professor: true,
    ativo: true,
    nome: "Eduardo Ariel Ponzio",
    curto: "Eduardo",
    siape: "1560291",
    celular: 0,
    cpf: 0,
    email: "eduardoariel@id.uff.br",
    sala: "307A",
    masculino: true,
  ),
  //
  fabi(
    key: 'fabi',
    professor: true,
    ativo: true,
    nome: "Fabiana Monteiro de Oliveira",
    curto: "Fabiana",
    siape: "1332073",
    celular: 0,
    cpf: 11198114738,
    email: "fabianaoliveira@id.uff.br",
    sala: "411",
    masculino: false,
  ),
  //
  joao(
    key: 'joao',
    professor: true,
    ativo: true,
    nome: "João Guilherme Siqueira Monteiro",
    curto: "João Guilherme",
    siape: "138090-2",
    celular: 0,
    cpf: 12336192764,
    email: "joao_guilherme@id.uff.br",
    sala: "303",
    masculino: true,
  ),
  //
  juli(
    key: 'juli',
    professor: true,
    ativo: true,
    nome: "Júlio César Martins da Silva",
    curto: "Júlio César",
    siape: "305929-1",
    celular: 0,
    cpf: 0,
    email: "juliocms@id.uff.br",
    sala: "307A",
    masculino: true,
  ),
  //
  kati(
    key: 'kati',
    professor: true,
    ativo: true,
    nome: "Kátia Zaccur Leal",
    curto: "Kátia",
    siape: "308719-0",
    celular: 0,
    cpf: 0,
    email: "katialeal@id.uff.br",
    sala: "513",
    masculino: false,
  ),
  //
  luca(
    key: 'luca',
    professor: true,
    ativo: true,
    nome: "Carlos Alberto Lucas",
    curto: "Lucas",
    siape: "310530-9",
    celular: 0,
    cpf: 0,
    email: "carloslucas@id.uff.br",
    sala: "303",
    masculino: true,
  ),
  //
  luci(
    key: 'luci',
    professor: true,
    ativo: true,
    nome: "Luciano Tavares da Costa",
    curto: "Luciano",
    siape: "171542-2",
    celular: 0,
    cpf: 0,
    email: "ltcosta@id.uff.br",
    sala: "309",
    masculino: true,
  ),
  //
  luiz(
    key: 'luiz',
    professor: true,
    ativo: true,
    nome: "Luiz Sérgio Radino Lamego",
    curto: "Luiz Sérgio",
    siape: "310914-2",
    celular: 0,
    cpf: 0,
    email: "luizlamego@id.uff.br",
    sala: "FV 101",
    masculino: true,
  ),
  //
  raph(
    key: 'raph',
    professor: true,
    ativo: true,
    nome: "Raphael da Costa Cruz",
    curto: "Raphael",
    siape: "253682-1",
    celular: 0,
    cpf: 0,
    email: "rccruz@id.uff.br",
    sala: "515",
    masculino: true,
  ),
  //
  robe(
    key: 'robe',
    professor: true,
    ativo: true,
    nome: "Roberto Carlos Alvim Cid",
    curto: "Roberto",
    siape: "303590-4",
    celular: 0,
    cpf: 0,
    email: "gfqrcid@vm.uff.br",
    sala: "303",
    masculino: true,
  ),
  //
  rosa(
    key: 'rosa',
    professor: true,
    ativo: false,
    nome: "Rosana Janot Martins",
    curto: "Rosana",
    siape: "310743-3",
    celular: 0,
    cpf: 0,
    email: "rjanot@id.uff.br",
    sala: "FV 101",
    masculino: false,
  ),
  //
  rose(
    key: 'rose',
    professor: true,
    ativo: true,
    nome: "Rose Mary Latini Cova",
    curto: "Rose",
    siape: "730739-8",
    celular: 0,
    cpf: 0,
    email: "roselatini@id.uff.br",
    sala: "411",
    masculino: false,
  ),
  //
  soni(
    key: 'soni',
    professor: true,
    ativo: true,
    nome: "Sonia Regina Alves Nogueira de Sá",
    curto: "Sonia",
    siape: "311646-7",
    celular: 0,
    cpf: 0,
    email: "sranogueiradesa@gmail.com",
    sala: "302A",
    masculino: false,
  ),
  //
  afra(
    key: 'afra',
    professor: false,
    ativo: true,
    nome: "José Afrânio Brenelli",
    curto: "José",
    siape: "1461790",
    celular: 0,
    cpf: 0,
    email: "jabrenelli@id.uff.br",
    sala: "L205",
    masculino: false,
  ),
  //
  heli(
    key: 'heli',
    professor: false,
    ativo: true,
    nome: "Hélio Ricardo Xavier Pimentel",
    curto: "Hélio",
    siape: "1072749-2",
    celular: 0,
    cpf: 0,
    email: "heliorxp@gmail.com",
    sala: "L205",
    masculino: true,
  ),
  //
/*   lici(
    key: 'lici',
    professor: false,
    ativo: true,
    nome: "Liciane Ferreira Plouvier",
    curto: "Liciane",
    siape: "1793483",
    celular: 0,
    cpf: 0,
    email: "liciane13@hotmail.com",
    sala: "L205",
    masculino: false,
  ),
  // */
  sedi(
    key: 'sedi',
    professor: false,
    ativo: true,
    nome: "Sedinir Consentini de Souza",
    curto: "Sedinir",
    siape: "1971386",
    celular: 0,
    cpf: 0,
    email: "sconsentini@id.uff.br",
    sala: "307",
    masculino: true,
  );

  final String key;
  final String nome;
  final String curto;
  final String siape;
  final int cpf;
  final int celular;
  final String email;
  final String sala;
  final bool masculino;
  final bool professor;
  final bool ativo;

  const Servidores({
    required this.key,
    required this.professor,
    required this.ativo,
    required this.nome,
    required this.curto,
    required this.siape,
    required this.cpf,
    required this.celular,
    required this.email,
    required this.sala,
    required this.masculino,
  });
}
